/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Store {
  'id' : string,
  'status' : string,
  'salesRep' : string,
  'revenue' : Array<number>,
  'name' : string,
  'subscriptionType' : string,
  'history' : string,
  'storeCode' : string,
  'brand' : string,
  'telephony' : string,
  'annualRevenue' : number,
}
export interface Task {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'storeId' : string,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'priority' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createTask' : ActorMethod<
    [string, string, string, string, string, bigint],
    undefined
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'fetchSheetCSV' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getStoreById' : ActorMethod<[string], Store>,
  'getStores' : ActorMethod<[], Array<Store>>,
  'getStoresByBrand' : ActorMethod<[string], Array<Store>>,
  'getStoresByStatus' : ActorMethod<[string], Array<Store>>,
  'getStoresBySubscription' : ActorMethod<[string], Array<Store>>,
  'getTasksByPriority' : ActorMethod<[string], Array<Task>>,
  'getTasksByStatus' : ActorMethod<[string], Array<Task>>,
  'getTasksByStore' : ActorMethod<[string], Array<Task>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];