/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'storeId' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'priority' : IDL.Text,
});
export const Store = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'salesRep' : IDL.Text,
  'revenue' : IDL.Vec(IDL.Float64),
  'name' : IDL.Text,
  'subscriptionType' : IDL.Text,
  'history' : IDL.Text,
  'storeCode' : IDL.Text,
  'brand' : IDL.Text,
  'telephony' : IDL.Text,
  'annualRevenue' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'fetchSheetCSV' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getStoreById' : IDL.Func([IDL.Text], [Store], ['query']),
  'getStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getStoresByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
  'getStoresByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
  'getStoresBySubscription' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
  'getTasksByPriority' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByStore' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'storeId' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'priority' : IDL.Text,
  });
  const Store = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'salesRep' : IDL.Text,
    'revenue' : IDL.Vec(IDL.Float64),
    'name' : IDL.Text,
    'subscriptionType' : IDL.Text,
    'history' : IDL.Text,
    'storeCode' : IDL.Text,
    'brand' : IDL.Text,
    'telephony' : IDL.Text,
    'annualRevenue' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'fetchSheetCSV' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getStoreById' : IDL.Func([IDL.Text], [Store], ['query']),
    'getStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getStoresByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
    'getStoresByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
    'getStoresBySubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Store)],
        ['query'],
      ),
    'getTasksByPriority' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByStore' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };